CREATE TABLE IF NOT EXISTS "private"."settings" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "key" text NOT NULL,
    "value" jsonb NOT NULL,
    "updated_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "settings_key_key" UNIQUE ("key"),
    CONSTRAINT "settings_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "private"."settings" OWNER TO "postgres";
ALTER TABLE "private"."settings" ENABLE ROW LEVEL SECURITY;




CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" uuid PRIMARY KEY REFERENCES "auth"."users"("id") ON DELETE CASCADE,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "deleted_at" timestamp with time zone,
    "history_enabled" boolean DEFAULT false NOT NULL
);
ALTER TABLE "public"."users" OWNER TO "postgres";
ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Policy with security definer functions" ON "public"."users" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "id"));




CREATE TABLE IF NOT EXISTS "public"."user_scores" (
    "user_id" uuid NOT NULL,
    "date" date NOT NULL,
    "item_count" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "deleted_at" timestamp with time zone,
    CONSTRAINT "user_scores_item_count_check" CHECK (("item_count" >= 0)),
    CONSTRAINT "user_score_pkey" PRIMARY KEY ("user_id", "date"),
    CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."user_scores" OWNER TO "postgres";
CREATE INDEX "idx_user_scores_updated_at" ON "public"."user_scores" USING "btree" ("updated_at");
CREATE INDEX "idx_user_scores_user_id_updated_at" ON "public"."user_scores" USING "btree" ("user_id", "updated_at");
CREATE OR REPLACE TRIGGER "trg_set_updated_at__user_scores" BEFORE UPDATE ON "public"."user_scores" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();
ALTER TABLE "public"."user_scores" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow regular users to modify their own data" ON "public"."user_scores" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));




CREATE TABLE IF NOT EXISTS "public"."blocks" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "note" text NOT NULL,
    "sort_order" integer NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "deleted_at" timestamp with time zone,
    CONSTRAINT "blocks_sort_order_check" CHECK (("sort_order" >= 1)),
    CONSTRAINT "blocks_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "blocks_sort_order_key" UNIQUE ("sort_order")
);
ALTER TABLE "public"."blocks" OWNER TO "postgres";
CREATE OR REPLACE TRIGGER "trg_set_updated_at__blocks" BEFORE UPDATE ON "public"."blocks" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();
ALTER TABLE "public"."blocks" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON "public"."blocks" FOR SELECT TO "authenticated" USING (true);




CREATE TABLE IF NOT EXISTS "public"."grammar" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "note" text NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "deleted_at" timestamp with time zone,
    "sort_order" integer NOT NULL,
    CONSTRAINT "grammar_sort_order_check" CHECK (("sort_order" >= 1)),
    CONSTRAINT "grammar_name_key" UNIQUE ("name"),
    CONSTRAINT "grammar_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."grammar" OWNER TO "postgres";
CREATE OR REPLACE TRIGGER "trg_set_updated_at__grammar" BEFORE UPDATE ON "public"."grammar" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();
ALTER TABLE "public"."grammar" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON "public"."grammar" FOR SELECT TO "authenticated" USING (true);



CREATE TABLE IF NOT EXISTS "public"."levels" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "deleted_at" timestamp with time zone,
    "sort_order" integer NOT NULL,
    "note" text NOT NULL,
    CONSTRAINT "levels_name_key" UNIQUE ("name"),
    CONSTRAINT "levels_sort_order_key" UNIQUE ("sort_order"),
    CONSTRAINT "levels_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."levels" OWNER TO "postgres";
CREATE INDEX "idx_levels_sort_order" ON "public"."levels" USING "btree" ("sort_order");
CREATE OR REPLACE TRIGGER "trg_set_updated_at__levels" BEFORE UPDATE ON "public"."levels" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();
ALTER TABLE "public"."levels" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON "public"."levels" FOR SELECT TO "authenticated" USING (true);




CREATE TABLE IF NOT EXISTS "public"."lessons" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "level_id" integer NOT NULL REFERENCES "public"."levels"("id") ON DELETE RESTRICT,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "deleted_at" timestamp with time zone,
    "sort_order" integer NOT NULL,
    "note" text NOT NULL,
    CONSTRAINT "lessons_name_key" UNIQUE ("name"),
    CONSTRAINT "lessons_sort_order_key" UNIQUE ("sort_order"),
    CONSTRAINT "lessons_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."lessons" OWNER TO "postgres";
CREATE INDEX "idx_lessons_level_id" ON "public"."lessons" USING "btree" ("level_id");
CREATE INDEX "idx_lessons_level_sort_order" ON "public"."lessons" USING "btree" ("level_id", "sort_order");
CREATE OR REPLACE TRIGGER "trg_set_updated_at__lessons" BEFORE UPDATE ON "public"."lessons" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();
ALTER TABLE "public"."lessons" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON "public"."lessons" FOR SELECT TO "authenticated" USING (true);




CREATE TABLE IF NOT EXISTS "public"."notes" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "note" text,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "deleted_at" timestamp with time zone,
    CONSTRAINT "notes_note_key" UNIQUE ("note"),
    CONSTRAINT "notes_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."notes" OWNER TO "postgres";
ALTER TABLE "public"."notes" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON "public"."notes" FOR SELECT TO "authenticated" USING (true);



CREATE TABLE IF NOT EXISTS "public"."items" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "czech" text NOT NULL,
    "english" text NOT NULL,
    "pronunciation" text,
    "audio" text,
    "sort_order" integer NOT NULL,
    "grammar_id" integer REFERENCES "public"."grammar"("id") ON DELETE SET NULL,
    "deleted_at" timestamp with time zone,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "lesson_id" integer NOT NULL REFERENCES "public"."lessons"("id") ON DELETE RESTRICT,
    "is_study_item" boolean DEFAULT true NOT NULL,
    "block_id" integer REFERENCES "public"."blocks"("id") ON DELETE SET NULL,
    "note_id" integer REFERENCES "public"."notes"("id") ON DELETE SET NULL,
    "is_vocabulary" boolean DEFAULT true NOT NULL,
    CONSTRAINT "items_sequence_check" CHECK (("sort_order" >= 0)),
    CONSTRAINT "items_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."items" OWNER TO "postgres";
CREATE INDEX "idx_items_block_id" ON "public"."items" USING "btree" ("block_id");
CREATE INDEX "idx_items_grammar_id" ON "public"."items" USING "btree" ("grammar_id");
CREATE INDEX "idx_items_lesson_id" ON "public"."items" USING "btree" ("lesson_id");
CREATE INDEX "idx_items_note_id" ON "public"."items" USING "btree" ("note_id");
CREATE INDEX "idx_items_updated_at" ON "public"."items" USING "btree" ("updated_at");
CREATE OR REPLACE TRIGGER "trg_set_updated_at__items" BEFORE UPDATE ON "public"."items" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();
ALTER TABLE "public"."items" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON "public"."items" FOR SELECT TO "authenticated" USING (true);



CREATE TABLE IF NOT EXISTS "public"."user_items" (
    "user_id" uuid NOT NULL REFERENCES "public"."users"("id") ON DELETE CASCADE,
    "item_id" integer NOT NULL REFERENCES "public"."items"("id") ON DELETE CASCADE,
    "progress" integer DEFAULT 0 NOT NULL,
    "started_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "next_at" timestamp with time zone,
    "mastered_at" timestamp with time zone,
    CONSTRAINT "user_items_progress_check" CHECK (("progress" >= 0)),
    CONSTRAINT "user_items_pkey" PRIMARY KEY ("user_id", "item_id")
);
ALTER TABLE "public"."user_items" OWNER TO "postgres";
CREATE INDEX "idx_user_items_item_user" ON "public"."user_items" USING "btree" ("item_id", "user_id") INCLUDE ("progress", "started_at", "updated_at", "next_at", "mastered_at");
CREATE INDEX "idx_user_items_updated_at" ON "public"."user_items" USING "btree" ("updated_at");
CREATE INDEX "idx_user_items_user_updated_item" ON "public"."user_items" USING "btree" ("user_id", "updated_at", "item_id") INCLUDE ("progress", "started_at", "next_at", "mastered_at");
CREATE OR REPLACE TRIGGER "trg_set_updated_at__user_items" BEFORE UPDATE ON "public"."user_items" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();
ALTER TABLE "public"."user_items" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow regular users to modify their own data" ON "public"."user_items" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));




CREATE TABLE IF NOT EXISTS "public"."user_items_history" (
    "item_id" integer NOT NULL REFERENCES "public"."items"("id") ON DELETE CASCADE,
    "user_id" uuid NOT NULL REFERENCES "public"."users"("id") ON DELETE CASCADE,
    "progress" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "user_items_history_progress_check" CHECK (("progress" >= 0)),
    CONSTRAINT "user_items_history_pkey" PRIMARY KEY ("user_id", "item_id", "created_at")
);
ALTER TABLE "public"."user_items_history" OWNER TO "postgres";
CREATE INDEX "idx_user_items_history_item_id" ON "public"."user_items_history" USING "btree" ("item_id");
ALTER TABLE "public"."user_items_history" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable insert for users based on user_id" ON "public"."user_items_history" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));