export const ROUTES = {
  home: '/',
  privacyPolicy: '/privacy-policy',
  practice: '/practice',
  practiceVocabulary: '/practice/vocabulary',
  practiceNewGrammar: '/practice/new-grammar',
  practiceGrammar: '/practice/grammar',
  practiceOverview: '/practice-overview',
  profile: '/profile',
  levels: '/levels',
  blocks: '/blocks',
  blocksDetail: '/blocks/:blockId',
  grammar: '/grammar',
  vocabulary: '/vocabulary',
  guide: '/guide',
};
