export const ROUTES = {
  home: '/',
  privacyPolicy: '/privacy-policy',
  practiceVocabulary: '/practice/vocabulary',
  practiceNewGrammar: '/practice/new-grammar',
  practiceGrammar: '/practice/grammar',
  practiceOverview: '/practice-overview',
  profile: '/profile',
  levels: '/levels',
  topics: '/topics',
  topicDetail: '/topics/:blockId',
  grammar: '/grammar',
  vocabulary: '/vocabulary',
  guide: '/guide',
};
