export const ROUTES = {
  home: '/',
  privacyPolicy: '/privacy-policy',
  practice: '/practice',
  practiceBlockTraining: '/practice/block-training',
  pronunciationPractice: '/practice/pronunciation',
  practiceOverview: '/practice-overview',
  overviews: '/overviews',
  profile: '/profile',
  levels: '/levels',
  topics: '/topics',
  topicDetail: '/topics/:topicId',
  grammar: '/grammar',
  vocabulary: '/vocabulary',
  pronunciationGroups: '/pronunciation',
  pronunciationGroup: '/pronunciation/:groupId',
  guide: '/guide',
};
